"""
This is a setup.py script generated by py2applet

Usage (OS X):
    python setup.py py2app

Usage (Windows):
    python setup.py py2exe
    

Edits by Pauli
"""
# Bootstrap
import ez_setup
ez_setup.use_setuptools()

import sys
import os
from setuptools import setup


# Common info
APP = 'siren.py'
version = '0.9.0'
DATA_FILES = ['DataWrapper.py',
'classGridTable.py',
'classMapView.py',
'classPreferencesDialog.py',
'classSiren.py',
'ez_setup.py',
'miscDialogs.py',
'ui_confdef.xml']

# Get SVN revision -- works w/o awk/grep/sed
svn_revision = '-1'
p = os.popen('svn info')
for line in p:
    l = line.split()
    if l[0] == 'Revision:':
        svn_revision = l[1]
        break
p.close()

if sys.platform == 'darwin':
    # A custom plist to associate with .siren -files
    Plist = dict(CFBundleDocumentTypes = [dict(CFBundleTypeExtensions=['siren'],
                                               CFBundleTypeName='Siren data file',
                                               CFBundleTypeRole = 'Viewer',
                                               CFBundleTypeIconFiles = 'siren_file_icon.icns'),
                                               ],
                CFBundleShortVersionString = version,
                CFBundleVersion = svn_revision,
                CFBundleName = 'Siren'
        )
    
    OPTIONS = {'argv_emulation': True,
    'iconfile': '/Users/pamietti/Documents/tyo/siren/icons/siren_icon.icns',
    'packages': ['wx', 'mpl_toolkits', 'reremi'],
    #'includes': ['ui_confdef.xml'], 
    #'includes': ['reremi'],
    'resources': ['icons', 'help', 'ABOUT', 'LICENSE', 'LICENSE_short', 'ui_confdef.xml', 'reremi/miner_confdef.xml'],
    'site_packages': True,
    #'semi-standalone': True, # depends on local Python
    'plist': Plist,
    }
    # Set extra options
    extra_options = dict(
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app']
        )
elif sys.platform == 'win32':
    ## Should this be 'win64'??
    print "Windows builds are not yet supported"

else:
    # Linux
    print "Linux builds are not yet supported"


setup(
    app=[APP],
    **extra_options
)
